ExUnit.start()
Ecto.Adapters.SQL.Sandbox.mode(DB.Repo, :manual)
Application.ensure_all_started(:bypass)
Application.ensure_all_started(:amorphos)
Amorphos.TestConnection.start_link()
Amorphos.TestMessageHandler.start_link()
