ExUnit.start()
Ecto.Adapters.SQL.Sandbox.mode(DB.Repo, :manual)
Application.ensure_all_started(:bypass)
Application.ensure_all_started(:ymp)
YMP.TestConnection.start_link()
YMP.TestMessageHandler.start_link()
